name: Build Certipy EXE

on:
  workflow_dispatch:
  push:
    branches: [ main, master ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.12

    - name: Upgrade pip, setuptools, wheel
      run: pip install --upgrade pip setuptools wheel

    - name: Install dependencies from pyproject.toml
      run: pip install .

    - name: Install PyInstaller
      run: pip install pyinstaller

    - name: Build EXE with PyInstaller
      run: pyinstaller Certipy.spec

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: Certipy-exe
        path: dist/Certipy.exe
